// Generated by https://quicktype.io

export interface DeleteUserbyAdminResponse {
    message:      string;
    deleteResult: DeleteResult;
}

export interface DeleteResult {
    fieldCount:   number;
    affectedRows: number;
    insertId:     number;
    serverStatus: number;
    warningCount: number;
    message:      string;
    protocol41:   boolean;
    changedRows:  number;
}
