// Generated by https://quicktype.io

export interface DeleteServiceResponse {
    message:             string;
    deleteServiceResult: DeleteServiceResult;
}

export interface DeleteServiceResult {
    fieldCount:   number;
    affectedRows: number;
    insertId:     number;
    serverStatus: number;
    warningCount: number;
    message:      string;
    protocol41:   boolean;
    changedRows:  number;
}
