// Generated by https://quicktype.io


export interface Service {
    service_id:               number;
    service_name:             string;
    service_description:      string;
    service_price:            number;
    service_approximate_time: string;
    userAdd:                  number;
}
